Repository 0chnxxx/Algorithm-Challenge, pull requests merged in 2024-10, with the labels that each got.

#1 [난이도2] 구름 찾기 깃발
  goorm/0chnxxx/난이도2_구름_찾기_깃발.kt
Labels: solve

#2 [난이도2] 문자열 나누기 2
  goorm/0chnxxx/난이도2_문자열_나누기_2.kt
Labels: solve

#4 [난이도2] 거울 단어
  goorm/0chnxxx/난이도2_거울_단어.kt
Labels: solve

#5 [GRM] 난이도1 / 인공지능 청소기 / 13분
  goorm/0chnxxx/난이도1_인공지능_청소기.kt
Labels: solve

#39 [BOJ] 난이도2 / 다리를 지나는 트럭 / 86분
  baekjoon/0chnxxx/다리를_지나는_트럭.kt
Labels: SOLVE

#38 [GRM] 난이도2 / 수열 / 6분
  goorm/0chnxxx/수열.kt
Labels: SOLVE

#37 [GRM] 난이도3 / 불이야!! / 56분
  goorm/0chnxxx/난이도3_불이야!!.kt
Labels: SOLVE

#36 [GRM] 난이도2 / 개미 집합의 지름 / 12분
  goorm/0chnxxx/개미_집합의_지름.kt
Labels: SOLVE

#35 [GRM] 난이도3 / ADAS 시스템 / 118분
  goorm/0chnxxx/난이도3_ADAS_시스템.kt
Labels: SOLVE

#34 [GRM] 난이도2 / 0커플 / 17분
  goorm/0chnxxx/난이도2_0커플.kt
Labels: SOLVE

#33 [GRM] 난이도3 / 거리두기 / 51분
  goorm/0chnxxx/난이도3_거리두기.kt
Labels: SOLVE

#32 [GRM] 난이도3 / 단풍나무 / 31분
  goorm/0chnxxx/난이도3_단풍나무.kt
Labels: SOLVE

#31 [GRM] 난이도1 / 정수의 길이 / 1분
  goorm/0chnxxx/정수의_길이.kt
Labels: SOLVE

#30 [GRM] 난이도2 / 거스름돈 / 5분
  goorm/0chnxxx/거스름돈.kt
Labels: SOLVE

#29 [GRM] 난이도2 / 구름스퀘어 / 32분
  goorm/0chnxxx/구름스퀘어.kt
Labels: SOLVE

#28 [GRM] 난이도2 / 블록 게임 / 41분
  goorm/0chnxxx/난이도2_블록_게임.kt
Labels: SOLVE

#27 [GRM] 난이도2 / 동전 퍼즐 / 62분
  goorm/0chnxxx/동전_퍼즐.kt
Labels: SOLVE

#26 [GRM] 난이도2 / 어려운 문제 / 16분
  goorm/0chnxxx/난이도2_어려운_문제.kt
Labels: SOLVE

#25 [GRM] 난이도2 / 계수기 만들기 / 39분
  goorm/0chnxxx/난이도2_계수기_만들기.kt
Labels: SOLVE

#24 [GRM] 난이도1 / 딱지놀이 / 25분
  goorm/0chnxxx/난이도1_딱지놀이.kt
Labels: SOLVE

#23 [GRM] 난이도1 / 소금물의 농도 구하기 / 23분
  goorm/0chnxxx/난이도1_소금물의_농도_구하기.kt
Labels: SOLVE

#20 [BOJ] Silver2~3 / 쿼드트리 / 45분
  baekjoon/pjkfckr/쿼드트리.py
Labels: SOLVE

#16 [BOJ] Silver2~3 / 색종이 만들기 / 30분
  baekjoon/pjkfckr/색종이_만들기.py
Labels: SOLVE

#40 [BOJ] 난이도2 / 카펫 / 39분
  baekjoon/0chnxxx/카펫.kt
Labels: SOLVE

#44 [PGS] 난이도2 / 귤 고르기 / 28분
  programmers/0chnxxx/귤_고르기.kt
  programmers/0chnxxx/다리를_지나는_트럭.kt
  programmers/0chnxxx/카펫.kt
Labels: SOLVE

#45 [PGS] 난이도2 / 연속 부분 수열 합의 계수 / 28분
  programmers/0chnxxx/연속_부분_수열_합의_개수.kt
Labels: SOLVE

#46 [PGS] 난이도2 / 할인 행사 / 27분
  programmers/0chnxxx/할인_행사.kt
Labels: SOLVE

#49 [PGS] 난이도2 / 롤케이크 자르기 / 14분
  programmers/0chnxxx/롤케이크_자르기.kt
Labels: SOLVE

#52 [PGS] 난이도2 / 뒤에 있는 큰 수 찾기 / 16분
  programmers/0chnxxx/뒤에_있는_큰_수_구하기.kt
Labels: SOLVE

#53 [PGS] 난이도2 / 롤케이크 자르기 / 20분
  programmers/pjkfckr/롤케이크_자르기.py
Labels: REFACTORING

#54 [LTC] Medium / 경로설정 / 15분
  leetcode/pjkfckr/Simplify_path.py
Labels: SOLVE

#55 [LTC] MEDIUM / Simplify Path / 53분
  leetcode/0chnxxx/Simplify_Path.kt
Labels: SOLVE

#56 [LTC] MEDIUM / SimplifyPath / 50분
  leetcode/BottlePumpkin/simplifyPath.py
Labels: SOLVE

#57 [LTC] Medium / 경로설정 / 30분
  leetcode/yeongi/simply_path.js
Labels: SOLVE

#58 [PGS] 난이도2 / 택배상자 / 13분
  programmers/0chnxxx/택배상자.kt
Labels: SOLVE

#59 [PGS] 난이도2 / 롤케이크 자르기 / 7분
  programmers/0chnxxx/롤케이크_자르기.kt
Labels: REFACTORING

#60 [PGS] 난이도2 / 숫자 변환하기 / 13분
  programmers/0chnxxx/숫자_변환하기.kt
Labels: SOLVE

#61 [PGS] 난이도2 / 삼각 달팽이 / 30분
  programmers/0chnxxx/삼각_달팽이.kt
Labels: SOLVE

#62 [PGS] 난이도2 / 연속된 부분 수열의 합 / 9분
  programmers/0chnxxx/연속된_부분_수열의_합.kt
Labels: SOLVE

#63 [BOJ] 난이도1 / 1로만들기 / 20분
  baekjoon/pjkfckr/1로_만들기.py
Labels: SOLVE

#64 [PGS] 난이도2 / 마법의 엘리베이터 / 38분
  programmers/0chnxxx/마법의_엘리베이터.kt
Labels: SOLVE

#65 [PGS] 난이도2 / 시소 짝꿍 / 39분
  programmers/0chnxxx/시소_짝꿍.kt
Labels: SOLVE

#66 [BOJ] 난이도1.5 / 계단오르기 / 35분
  baekjoon/pjkfckr/계단오르기.py
Labels: SOLVE

#67 [PGS] 난이도1 / 추억 점수 / 20분
  programmers/0chnxxx/추억_점수.kt
Labels: SOLVE

#68 [BOJ] 난이도1.5 / 트리순회 / 30분
  baekjoon/pjkfckr/트리_순회.py
Labels: SOLVE

#69 [PGS] 난이도1 / 카드 뭉치 / 10분
  programmers/0chnxxx/카드_뭉치.kt
Labels: SOLVE

#70 [PGS] 난이도1 / 덧칠하기 / 13분
  programmers/0chnxxx/덧칠하기.kt
Labels: SOLVE

#71 [PGS] 난이도1 / 대충 만든 자판 / 18분
  programmers/0chnxxx/대충_만든_자판.kt
Labels: SOLVE
